<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title>Internal Server Error</title>
        <style>
            body {
    font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;
    font-size: .813em;
    color: #222;
    background-color: #fff;
}

h1, h2, h3, h4, h5 {
    /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
    font-weight: 100;
}

h1 {
    color: #44525e;
    margin: 15px 0 15px 0;
}

h2 {
    margin: 10px 5px 0 0;
}

h3 {
    color: #363636;
    margin: 5px 5px 0 0;
}

code {
    font-family: Consolas, "Courier New", courier, monospace;
}

body .titleerror {
    padding: 3px 3px 6px 3px;
    display: block;
    font-size: 1.5em;
    font-weight: 100;
}

body .location {
    margin: 3px 0 10px 30px;
}

#header {
    font-size: 18px;
    padding: 15px 0;
    border-top: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
    margin-bottom: 0;
}

    #header li {
        display: inline;
        margin: 5px;
        padding: 5px;
        color: #a0a0a0;
        cursor: pointer;
    }

    #header .selected {
        background: #44c5f2;
        color: #fff;
    }

#stackpage ul {
    list-style: none;
    padding-left: 0;
    margin: 0;
    /*border-bottom: 1px #ddd solid;*/
}

#stackpage .details {
    font-size: 1.2em;
    padding: 3px;
    color: #000;
}

#stackpage .stackerror {
    padding: 5px;
    border-bottom: 1px #ddd solid;
}


#stackpage .frame {
    padding: 0;
    margin: 0 0 0 30px;
}

    #stackpage .frame h3 {
        padding: 2px;
        margin: 0;
    }

#stackpage .source {
    padding: 0 0 0 30px;
}

    #stackpage .source ol li {
        font-family: Consolas, "Courier New", courier, monospace;
        white-space: pre;
        background-color: #fbfbfb;
    }

#stackpage .frame .source .highlight li span {
    color: #FF0000;
}

#stackpage .source ol.collapsible li {
    color: #888;
}

    #stackpage .source ol.collapsible li span {
        color: #606060;
    }

.page table {
    border-collapse: separate;
    border-spacing: 0;
    margin: 0 0 20px;
}

.page th {
    vertical-align: bottom;
    padding: 10px 5px 5px 5px;
    font-weight: 400;
    color: #a0a0a0;
    text-align: left;
}

.page td {
    padding: 3px 10px;
}

.page th, .page td {
    border-right: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
    border-left: 1px transparent solid;
    border-top: 1px transparent solid;
    box-sizing: border-box;
}

    .page th:last-child, .page td:last-child {
        border-right: 1px transparent solid;
    }

.page .length {
    text-align: right;
}

a {
    color: #1ba1e2;
    text-decoration: none;
}

    a:hover {
        color: #13709e;
        text-decoration: underline;
    }

.showRawException {
    cursor: pointer;
    color: #44c5f2;
    background-color: transparent;
    font-size: 1.2em;
    text-align: left;
    text-decoration: none;
    display: inline-block;
    border: 0;
    padding: 0;
}

.rawExceptionStackTrace {
    font-size: 1.2em;
}

.rawExceptionBlock {
    border-top: 1px #ddd solid;
    border-bottom: 1px #ddd solid;
}

.showRawExceptionContainer {
    margin-top: 10px;
    margin-bottom: 10px;
}

.expandCollapseButton {
    cursor: pointer;
    float: left;
    height: 16px;
    width: 16px;
    font-size: 10px;
    position: absolute;
    left: 10px;
    background-color: #eee;
    padding: 0;
    border: 0;
    margin: 0;
}

        </style>
    </head>
    <body>
        <h1>An unhandled exception occurred while processing the request.</h1>
            <div class="titleerror">Win32Exception: An attempt was made to access a socket in a way forbidden by its access permissions</div>
                <p class="location">Unknown location</p>
            <div class="titleerror">SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - An attempt was made to access a socket in a way forbidden by its access permissions.)</div>
                <p class="location">System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, object providerInfo, bool redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, bool applyTransientFaultHandling)</p>
        <ul id="header">
            <li id="stack" tabindex="1" class="selected">
                Stack
            </li>
            <li id="query" tabindex="2">
                Query
            </li>
            <li id="cookies" tabindex="3">
                Cookies
            </li>
            <li id="headers" tabindex="4">
                Headers
            </li>
        </ul>

        <div id="stackpage" class="page">
            <ul>
                                    <li>
                        <h2 class="stackerror">Win32Exception: An attempt was made to access a socket in a way forbidden by its access permissions</h2>
                        <ul>
                        </ul>
                    </li>
                    <li>
                        <br/>
                        <div class="rawExceptionBlock">
                            <div class="showRawExceptionContainer">
                                <button class="showRawException" data-exceptionDetailId="exceptionDetail1">Show raw exception details</button>
                            </div>
                            <div id="exceptionDetail1" class="rawExceptionDetails">
                                <pre class="rawExceptionStackTrace">System.ComponentModel.Win32Exception (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions</pre>
                            </div>
                        </div>
                    </li>
                    <li>
                        <h2 class="stackerror">SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - An attempt was made to access a socket in a way forbidden by its access permissions.)</h2>
                        <ul>
                            <li class="frame" id="frame1">
                                    <h3>System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, object providerInfo, bool redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, bool applyTransientFaultHandling)</h3>

                            </li>
                            <li class="frame" id="frame2">
                                    <h3>System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)</h3>

                            </li>
                            <li class="frame" id="frame3">
                                    <h3>System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)</h3>

                            </li>
                            <li class="frame" id="frame4">
                                    <h3>System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)</h3>

                            </li>
                            <li class="frame" id="frame5">
                                    <h3>System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)</h3>

                            </li>
                            <li class="frame" id="frame6">
                                    <h3>System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, uint waitForMultipleObjectsTimeout, bool allowCreate, bool onlyOneCheckConnection, DbConnectionOptions userOptions, out DbConnectionInternal connection)</h3>

                            </li>
                            <li class="frame" id="frame7">
                                    <h3>System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource&lt;DbConnectionInternal&gt; retry, DbConnectionOptions userOptions, out DbConnectionInternal connection)</h3>

                            </li>
                            <li class="frame" id="frame8">
                                    <h3>System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource&lt;DbConnectionInternal&gt; retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, out DbConnectionInternal connection)</h3>

                            </li>
                            <li class="frame" id="frame9">
                                    <h3>System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource&lt;DbConnectionInternal&gt; retry, DbConnectionOptions userOptions)</h3>

                            </li>
                            <li class="frame" id="frame10">
                                    <h3>System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource&lt;DbConnectionInternal&gt; retry, DbConnectionOptions userOptions)</h3>

                            </li>
                            <li class="frame" id="frame11">
                                    <h3>System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource&lt;DbConnectionInternal&gt; retry)</h3>

                            </li>
                            <li class="frame" id="frame12">
                                    <h3>System.Data.SqlClient.SqlConnection.Open()</h3>

                            </li>
                            <li class="frame" id="frame13">
                                    <h3>Dapper.SqlMapper&#x2B;&lt;QueryImpl&gt;d__138.MoveNext() in <code title="C:\projects\dapper\Dapper\SqlMapper.cs">SqlMapper.cs</code></h3>

                            </li>
                            <li class="frame" id="frame14">
                                    <h3>System.Collections.Generic.List.AddEnumerable(IEnumerable&lt;T&gt; enumerable)</h3>

                            </li>
                            <li class="frame" id="frame15">
                                    <h3>System.Collections.Generic.List..ctor(IEnumerable&lt;T&gt; collection)</h3>

                            </li>
                            <li class="frame" id="frame16">
                                    <h3>System.Linq.Enumerable.ToList&lt;TSource&gt;(IEnumerable&lt;TSource&gt; source)</h3>

                            </li>
                            <li class="frame" id="frame17">
                                    <h3>Dapper.SqlMapper.Query&lt;T&gt;(IDbConnection cnn, string sql, object param, IDbTransaction transaction, bool buffered, Nullable&lt;int&gt; commandTimeout, Nullable&lt;CommandType&gt; commandType) in <code title="C:\projects\dapper\Dapper\SqlMapper.cs">SqlMapper.cs</code></h3>

                            </li>
                            <li class="frame" id="frame18">
                                    <h3>LeafLogixPublicAPI.Services.StoredProcedureParameterMapper.CacheOne(string qualifiedProcedureName) in <code title="C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Services\StoredProcedureParameterMapper.cs">StoredProcedureParameterMapper.cs</code></h3>

                            </li>
                            <li class="frame" id="frame19">
                                    <h3>LeafLogixPublicAPI.Services.StoredProcedureParameterMapper.Map(string qualifiedStoredProcedureName, object parameters, bool nullMissingValues) in <code title="C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Services\StoredProcedureParameterMapper.cs">StoredProcedureParameterMapper.cs</code></h3>

                            </li>
                            <li class="frame" id="frame20">
                                    <h3>LeafLogixPublicAPI.Services.LeafLogixDatabase.QueryMultiple(string querySql) in <code title="C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Services\LeafLogixDatabase.cs">LeafLogixDatabase.cs</code></h3>

                            </li>
                            <li class="frame" id="frame21">
                                    <h3>LeafLogixPublicAPI.Controllers.InventoryController.GetInventory(bool includeLabResults) in <code title="C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Controllers\InventoryController.cs">InventoryController.cs</code></h3>

                            </li>
                            <li class="frame" id="frame22">
                                    <h3>lambda_method(Closure , object , Object[] )</h3>

                            </li>
                            <li class="frame" id="frame23">
                                    <h3>Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, Object[] parameters)</h3>

                            </li>
                            <li class="frame" id="frame24">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker&#x2B;&lt;InvokeActionMethodAsync&gt;d__12.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame25">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame26">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" id="frame27">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame28">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker&#x2B;&lt;InvokeNextActionFilterAsync&gt;d__10.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame29">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame30">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)</h3>

                            </li>
                            <li class="frame" id="frame31">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)</h3>

                            </li>
                            <li class="frame" id="frame32">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker&#x2B;&lt;InvokeInnerFilterAsync&gt;d__14.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame33">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame34">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" id="frame35">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame36">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker&#x2B;&lt;InvokeNextResourceFilter&gt;d__22.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame37">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame38">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)</h3>

                            </li>
                            <li class="frame" id="frame39">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)</h3>

                            </li>
                            <li class="frame" id="frame40">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker&#x2B;&lt;InvokeFilterPipelineAsync&gt;d__17.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame41">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame42">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" id="frame43">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame44">
                                    <h3>Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker&#x2B;&lt;InvokeAsync&gt;d__15.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame45">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame46">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" id="frame47">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame48">
                                    <h3>Microsoft.AspNetCore.Builder.RouterMiddleware&#x2B;&lt;Invoke&gt;d__4.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame49">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame50">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" id="frame51">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame52">
                                    <h3>Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware&#x2B;&lt;Invoke&gt;d__6.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame53">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame54">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" id="frame55">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame56">
                                    <h3>Microsoft.AspNetCore.Authentication.AuthenticationMiddleware&#x2B;&lt;Invoke&gt;d__6.MoveNext()</h3>

                            </li>
                            <li class="frame" id="frame57">
                                    <h3>System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()</h3>

                            </li>
                            <li class="frame" id="frame58">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)</h3>

                            </li>
                            <li class="frame" id="frame59">
                                    <h3>System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)</h3>

                            </li>
                            <li class="frame" id="frame60">
                                    <h3>Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware&#x2B;&lt;Invoke&gt;d__7.MoveNext()</h3>

                            </li>
                        </ul>
                    </li>
                    <li>
                        <br/>
                        <div class="rawExceptionBlock">
                            <div class="showRawExceptionContainer">
                                <button class="showRawException" data-exceptionDetailId="exceptionDetail2">Show raw exception details</button>
                            </div>
                            <div id="exceptionDetail2" class="rawExceptionDetails">
                                <pre class="rawExceptionStackTrace">System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - An attempt was made to access a socket in a way forbidden by its access permissions.) ---&gt; System.ComponentModel.Win32Exception (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions&#xD;&#xA;   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)&#xD;&#xA;   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)&#xD;&#xA;   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)&#xD;&#xA;   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)&#xD;&#xA;   at System.Data.SqlClient.SqlConnection.Open()&#xD;&#xA;   at Dapper.SqlMapper.&lt;QueryImpl&gt;d__138`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:line 1080&#xD;&#xA;   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)&#xD;&#xA;   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)&#xD;&#xA;   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)&#xD;&#xA;   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 723&#xD;&#xA;   at LeafLogixPublicAPI.Services.StoredProcedureParameterMapper.CacheOne(String qualifiedProcedureName) in C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Services\StoredProcedureParameterMapper.cs:line 83&#xD;&#xA;   at LeafLogixPublicAPI.Services.StoredProcedureParameterMapper.Map(String qualifiedStoredProcedureName, Object parameters, Boolean nullMissingValues) in C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Services\StoredProcedureParameterMapper.cs:line 35&#xD;&#xA;   at LeafLogixPublicAPI.Services.LeafLogixDatabase.QueryMultiple(String querySql) in C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Services\LeafLogixDatabase.cs:line 29&#xD;&#xA;   at LeafLogixPublicAPI.Controllers.InventoryController.GetInventory(Boolean includeLabResults) in C:\git\leaflogix\PublicAPI\LeafLogixPublicAPI\Controllers\InventoryController.cs:line 32&#xD;&#xA;   at lambda_method(Closure , Object , Object[] )&#xD;&#xA;   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;d__12.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;d__10.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeInnerFilterAsync&gt;d__14.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.&lt;InvokeNextResourceFilter&gt;d__22.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.&lt;InvokeFilterPipelineAsync&gt;d__17.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.&lt;InvokeAsync&gt;d__15.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at Microsoft.AspNetCore.Builder.RouterMiddleware.&lt;Invoke&gt;d__4.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.&lt;Invoke&gt;d__6.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.&lt;Invoke&gt;d__6.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.&lt;Invoke&gt;d__7.MoveNext()&#xD;&#xA;ClientConnectionId:00000000-0000-0000-0000-000000000000&#xD;&#xA;Error Number:10013,State:0,Class:20</pre>
                            </div>
                        </div>
                    </li>
            </ul>
        </div>

        <div id="querypage" class="page">
                <p>No QueryString data.</p>
        </div>

        <div id="cookiespage" class="page">
                <p>No cookie data.</p>
        </div>
        <div id="headerspage" class="page">
                <table>
                    <thead>
                        <tr>
                            <th>Variable</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tbody>
                                <tr>
                                    <td>Accept</td>
                                    <td>*/*</td>
                                </tr>
                                <tr>
                                    <td>Accept-Encoding</td>
                                    <td>gzip, deflate</td>
                                </tr>
                                <tr>
                                    <td>Authorization</td>
                                    <td>Basic MDk0YmI1Yjc5ZWM5NGZiOTk5MGRjMzRiZjQwYzEwNDM=</td>
                                </tr>
                                <tr>
                                    <td>CLIENT-IP</td>
                                    <td>173.79.4.42:62408</td>
                                </tr>
                                <tr>
                                    <td>Connection</td>
                                    <td>Keep-Alive</td>
                                </tr>
                                <tr>
                                    <td>DISGUISED-HOST</td>
                                    <td>leaflogix-publicapi-test.azurewebsites.net</td>
                                </tr>
                                <tr>
                                    <td>Host</td>
                                    <td>leaflogix-publicapi-test.azurewebsites.net</td>
                                </tr>
                                <tr>
                                    <td>Max-Forwards</td>
                                    <td>10</td>
                                </tr>
                                <tr>
                                    <td>MS-ASPNETCORE-TOKEN</td>
                                    <td>5474c583-ba51-4f8c-8cd2-b7c61860e838</td>
                                </tr>
                                <tr>
                                    <td>User-Agent</td>
                                    <td>python-requests/2.18.4</td>
                                </tr>
                                <tr>
                                    <td>WAS-DEFAULT-HOSTNAME</td>
                                    <td>leaflogix-publicapi-test.azurewebsites.net</td>
                                </tr>
                                <tr>
                                    <td>X-ARR-LOG-ID</td>
                                    <td>23950af6-280c-42d5-b524-4b168cc2862f</td>
                                </tr>
                                <tr>
                                    <td>X-Forwarded-For</td>
                                    <td>173.79.4.42:62408</td>
                                </tr>
                                <tr>
                                    <td>X-Original-For</td>
                                    <td>127.0.0.1:50292</td>
                                </tr>
                                <tr>
                                    <td>X-Original-Proto</td>
                                    <td>http</td>
                                </tr>
                                <tr>
                                    <td>X-Original-URL</td>
                                    <td>/inventory/</td>
                                </tr>
                                <tr>
                                    <td>X-SITE-DEPLOYMENT-ID</td>
                                    <td>LeafLogix-PublicAPI-Test</td>
                                </tr>
                                <tr>
                                    <td>X-WAWS-Unencoded-URL</td>
                                    <td>/inventory/</td>
                                </tr>
                    </tbody>
                </table>
        </div>
        <script>
            //<!--
            (function (window, undefined) {
    "use strict";

    function ns(selector, element) {
        return new NodeCollection(selector, element);
    }

    function NodeCollection(selector, element) {
        this.items = [];
        element = element || window.document;

        var nodeList;

        if (typeof (selector) === "string") {
            nodeList = element.querySelectorAll(selector);
            for (var i = 0, l = nodeList.length; i < l; i++) {
                this.items.push(nodeList.item(i));
            }
        }
    }

    NodeCollection.prototype = {
        each: function (callback) {
            for (var i = 0, l = this.items.length; i < l; i++) {
                callback(this.items[i], i);
            }
            return this;
        },

        children: function (selector) {
            var children = [];

            this.each(function (el) {
                children = children.concat(ns(selector, el).items);
            });

            return ns(children);
        },

        hide: function () {
            this.each(function (el) {
                el.style.display = "none";
            });

            return this;
        },

        toggle: function () {
            this.each(function (el) {
                el.style.display = el.style.display === "none" ? "" : "none";
            });

            return this;
        },

        show: function () {
            this.each(function (el) {
                el.style.display = "";
            });

            return this;
        },

        addClass: function (className) {
            this.each(function (el) {
                var existingClassName = el.className,
                    classNames;
                if (!existingClassName) {
                    el.className = className;
                } else {
                    classNames = existingClassName.split(" ");
                    if (classNames.indexOf(className) < 0) {
                        el.className = existingClassName + " " + className;
                    }
                }
            });

            return this;
        },

        removeClass: function (className) {
            this.each(function (el) {
                var existingClassName = el.className,
                    classNames, index;
                if (existingClassName === className) {
                    el.className = "";
                } else if (existingClassName) {
                    classNames = existingClassName.split(" ");
                    index = classNames.indexOf(className);
                    if (index > 0) {
                        classNames.splice(index, 1);
                        el.className = classNames.join(" ");
                    }
                }
            });

            return this;
        },

        attr: function (name) {
            if (this.items.length === 0) {
                return null;
            }

            return this.items[0].getAttribute(name);
        },

        on: function (eventName, handler) {
            this.each(function (el, idx) {
                var callback = function (e) {
                    e = e || window.event;
                    if (!e.which && e.keyCode) {
                        e.which = e.keyCode; // Normalize IE8 key events
                    }
                    handler.apply(el, [e]);
                };

                if (el.addEventListener) { // DOM Events
                    el.addEventListener(eventName, callback, false);
                } else if (el.attachEvent) { // IE8 events
                    el.attachEvent("on" + eventName, callback);
                } else {
                    el["on" + type] = callback;
                }
            });

            return this;
        },

        click: function (handler) {
            return this.on("click", handler);
        },

        keypress: function (handler) {
            return this.on("keypress", handler);
        }
    };

    function frame(el) {
        ns(".source .collapsible", el).toggle();
    }

    function expandCollapseButton(el) {
        var frameId = el.getAttribute("data-frameId");
        frame(document.getElementById(frameId));
        if (el.innerText === "+") {
            el.innerText = "-";
        }
        else {
            el.innerText = "+";
        }
    }

    function tab(el) {
        var unselected = ns("#header .selected").removeClass("selected").attr("id");
        var selected = ns("#" + el.id).addClass("selected").attr("id");

        ns("#" + unselected + "page").hide();
        ns("#" + selected + "page").show();
    }

    ns(".rawExceptionDetails").hide();
    ns(".collapsible").hide();
    ns(".page").hide();
    ns("#stackpage").show();

    ns(".expandCollapseButton")
        .click(function () {
            expandCollapseButton(this);
        })
        .keypress(function (e) {
            if (e.which === 13) {
                expandCollapseButton(this);
            }
        });

    ns("#header li")
        .click(function () {
            tab(this);
        })
        .keypress(function (e) {
            if (e.which === 13) {
                tab(this);
            }
        });

    ns(".showRawException")
        .click(function () {
            var exceptionDetailId = this.getAttribute("data-exceptionDetailId");
            ns("#" + exceptionDetailId).toggle();
        });
})(window);
            //-->
        </script>
    </body>
</html>

